[phases.setup]
nixPkgs = ["nodejs_20"]
cmds = [
	"corepack enable",
	"corepack prepare yarn@stable --activate"
]

[phases.install]
cmds = ["npm install --prefer-offline --no-audit"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=2048"
